config/routes.rb
Myproject::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :blogs

  mount Ckeditor::Engine => '/ckeditor'

  resources :assets

  resources :import_tables

  get "csv/import"

  resources :places

  resources :people
  match '/tinymce_assets', to: 'tinymce_assets#create'
    resources :upload
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :stores
    resources :articles do
      resources :comments
    end

    resources :microposts
    resources :products do
      get :who_bought, :on => :member
    end
    root to: "store#index"
    match '/adminitrator', to: 'admin#index'
    get "users/new"
    match '/signup',  to: 'users#new'
    match '/help',    to: 'static_pages#help'
    match '/about',   to: 'static_pages#about'
    match '/contact', to: 'static_pages#contact'
    match '/books', to: 'layouts#book'

  get "say/hello"

  get "say/goodbye"
  mount Ckeditor::Engine => "/ckeditor"
 

end

app/controllers/import_tables_controller.rb
class ImportTablesController < ApplicationController
  # GET /import_tables
  # GET /import_tables.json
  def index
    @import_tables = ImportTable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @import_tables }
    end
  end

  # GET /import_tables/1
  # GET /import_tables/1.json
  def show
    
    @import_table = ImportTable.find(params[:id])
    @import_cells = @import_table.import_cells
    @row_index_max = @import_cells.map { |cell| cell.row_index }.max
    @column_index_max = @import_cells.map { |cell| cell.column_index }.max

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @import_table }
    end
  end

  # GET /import_tables/new
  # GET /import_tables/new.json
  def new
    @import_table = ImportTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @import_table }
    end
  end

  # GET /import_tables/1/edit
  def edit
    @import_table = ImportTable.find(params[:id])
  end

  # POST /import_tables
  # POST /import_tables.json
  def create
    @import_table = ImportTable.new(params[:import_table])

    respond_to do |format|
      if @import_table.save
        format.html { redirect_to @import_table, notice: 'Import table was successfully created.' }
        format.json { render json: @import_table, status: :created, location: @import_table }
      else
        format.html { render action: "new" }
        format.json { render json: @import_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /import_tables/1
  # PUT /import_tables/1.json
  def update
    @import_table = ImportTable.find(params[:id])

    respond_to do |format|
      if @import_table.update_attributes(params[:import_table])
        format.html { redirect_to @import_table, notice: 'Import table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @import_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /import_tables/1
  # DELETE /import_tables/1.json
  def destroy
    @import_table = ImportTable.find(params[:id])
    @import_table.destroy

    respond_to do |format|
      format.html { redirect_to import_tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/import_tables_helper.rb
module ImportTablesHelper
end

app/views/import_tables/_form.html.erb
<%= form_for(@import_table) do |f| %>
  <% if @import_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import_table.errors.count, "error") %> prohibited this import_table from being saved:</h2>

      <ul>
      <% @import_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :original_path %><br />
    <%= f.text_field :original_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/import_tables/edit.html.erb
<h1>Editing import_table</h1>

<%= render 'form' %>

<%= link_to 'Show', @import_table %> |
<%= link_to 'Back', import_tables_path %>

app/views/import_tables/index.html.erb
<h1>Listing import_tables</h1>

<table>
  <tr>
    <th>Original path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @import_tables.each do |import_table| %>
  <tr>
    <td><%= import_table.original_path %></td>
    <td><%= link_to 'Show', import_table %></td>
    <td><%= link_to 'Edit', edit_import_table_path(import_table) %></td>
    <td><%= link_to 'Destroy', import_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Import table', new_import_table_path %>

app/views/import_tables/new.html.erb
<h1>New import_table</h1>

<%= render 'form' %>

<%= link_to 'Back', import_tables_path %>

app/views/import_tables/show.html.erb
<table border="1" cellspacing="1" cellpadding="1">
  <% 0.upto(@row_index_max) do |row_index| %>
    <% row = @import_cells.select { |cell| cell.row_index == row_index } %>
    <tr>
      <% 0.upto(@column_index_max) do |column_index| %>
        <td>
          <%= row.select { |cell| cell.column_index == column_index }[0].contents %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>